This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/miriam/work/PhD/Manuscripts/PhDthesis/central.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/miriam/work/PhD/Manuscripts/PhDthesis/central.acn....done (50 entries accepted, 0 rejected).
Sorting entries....done (312 comparisons).
Generating output file /Users/miriam/work/PhD/Manuscripts/PhDthesis/central.acr....done (52 lines written, 0 warnings).
Output written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/central.acr.
Transcript written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/central.alg.
