This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/miriam/work/PhD/Manuscripts/PhDthesis/SF_only.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/miriam/work/PhD/Manuscripts/PhDthesis/SF_only.acn....done (49 entries accepted, 0 rejected).
Sorting entries....done (271 comparisons).
Generating output file /Users/miriam/work/PhD/Manuscripts/PhDthesis/SF_only.acr....done (39 lines written, 0 warnings).
Output written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/SF_only.acr.
Transcript written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/SF_only.alg.
