This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/miriam/work/PhD/Manuscripts/PhDthesis/pre-change/current/central.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/miriam/work/PhD/Manuscripts/PhDthesis/pre-change/current/central.acn....done (301 entries accepted, 0 rejected).
Sorting entries.....done (2849 comparisons).
Generating output file /Users/miriam/work/PhD/Manuscripts/PhDthesis/pre-change/current/central.acr....done (144 lines written, 0 warnings).
Output written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/pre-change/current/central.acr.
Transcript written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/pre-change/current/central.alg.
