This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/miriam/work/PhD/Manuscripts/PhDthesis/.texpadtmp/central.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/miriam/work/PhD/Manuscripts/PhDthesis/.texpadtmp/central.acn....done (246 entries accepted, 0 rejected).
Sorting entries.....done (2132 comparisons).
Generating output file /Users/miriam/work/PhD/Manuscripts/PhDthesis/.texpadtmp/central.acr....done (111 lines written, 0 warnings).
Output written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/.texpadtmp/central.acr.
Transcript written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/.texpadtmp/central.alg.
