This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/miriam/work/PhD/Manuscripts/PhDthesis/individual_chapters/ABCFlow_only/ABCFlow_only.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/miriam/work/PhD/Manuscripts/PhDthesis/individual_chapters/ABCFlow_only/ABCFlow_only.acn....done (113 entries accepted, 0 rejected).
Sorting entries....done (873 comparisons).
Generating output file /Users/miriam/work/PhD/Manuscripts/PhDthesis/individual_chapters/ABCFlow_only/ABCFlow_only.acr....done (48 lines written, 0 warnings).
Output written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/individual_chapters/ABCFlow_only/ABCFlow_only.acr.
Transcript written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/individual_chapters/ABCFlow_only/ABCFlow_only.alg.
