This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/chSysBio-Switches-ML/central.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/chSysBio-Switches-ML/central.acn....done (287 entries accepted, 0 rejected).
Sorting entries.....done (2406 comparisons).
Generating output file /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/chSysBio-Switches-ML/central.acr....done (127 lines written, 0 warnings).
Output written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/chSysBio-Switches-ML/central.acr.
Transcript written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/chSysBio-Switches-ML/central.alg.
