This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/current/central.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/current/central.acn....done (341 entries accepted, 0 rejected).
Sorting entries......done (3088 comparisons).
Generating output file /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/current/central.acr....done (152 lines written, 0 warnings).
Output written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/current/central.acr.
Transcript written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/Complete_thesis/current/central.alg.
