This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/miriam/work/PhD/Manuscripts/PhDthesis/chExp-01-07-16-miriam/central.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/miriam/work/PhD/Manuscripts/PhDthesis/chExp-01-07-16-miriam/central.acn....done (247 entries accepted, 0 rejected).
Sorting entries.....done (2157 comparisons).
Generating output file /Users/miriam/work/PhD/Manuscripts/PhDthesis/chExp-01-07-16-miriam/central.acr....done (111 lines written, 0 warnings).
Output written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/chExp-01-07-16-miriam/central.acr.
Transcript written in /Users/miriam/work/PhD/Manuscripts/PhDthesis/chExp-01-07-16-miriam/central.alg.
